name: mysql-phpmyadmin

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: my_database # Nombre de la base de datos inicial
      MYSQL_USER: user            # Usuario personalizado
      MYSQL_PASSWORD: user_password # Contraseña del usuario
    ports:
      - "3306:3306"
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql # Nombre del servicio MySQL (debe coincidir con el "container_name" o servicio de MySQL)
      PMA_PORT: 3306  # Puerto de MySQL
      PMA_USER: root  # Usuario de MySQL
      PMA_PASSWORD: 123456789 # Contraseña del usuario de MySQL
    ports:
      - "80:80" # phpMyAdmin estará disponible en el puerto 8080
    restart: always


